import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const en = {
  app: { name: 'EduAllocPro', tagline: 'School Intelligence & Teacher Deployment' },
  nav: {
    dashboard: 'Dashboard', deploy: 'Deploy Teachers', plan: 'District Plan',
    briefing: 'AI Briefing', schools: 'Schools', teachers: 'Teachers', settings: 'Settings',
  },
  dashboard: {
    title: 'District Command', district: 'Nandurbar District, Maharashtra',
    vacancies: 'Open Vacancies', critical: 'Critical Schools', rte: 'RTE Violations', deployments: 'Deployments This Week',
    rankedSchools: 'Schools Ranked by Deprivation Index', search: 'Search 847 schools…', filters: 'Filters',
    seeAll: 'See all 847', live: 'LIVE',
  },
  school: {
    diScore: 'Deprivation Index', dvs: 'Deployment Value Score', rteViolation: 'RTE Violation',
    vacancies: 'Subject Vacancies', udise: 'UDISE+ Data', updated: 'Updated', deployTeacher: 'Deploy Teacher',
    viewBriefing: 'View Briefing', critical: 'CRITICAL', high: 'HIGH NEED', moderate: 'MODERATE', stable: 'STABLE',
    pupils: 'Pupils', teachers: 'Teachers', ratio: 'PTR',
  },
  deploy: {
    title: 'Teacher Deployment', subtitle: 'AI-ranked candidates for {{school}}',
    matchScore: 'Match Score', distance: 'Distance', retention: 'Retention', experience: 'Experience',
    approve: 'Approve Deployment', undo: 'Undo', deployed: 'Deployment approved · undo within 30s',
    rank: 'Rank', subject: 'Subject', currentPosting: 'Current Posting',
  },
  plan: {
    title: 'District Deployment Plan', subtitle: '{{count}} pending assignments',
    bulkApprove: 'Bulk Approve Selected', selected: '{{n}} selected',
  },
  briefing: { title: 'AI District Briefing', generated: 'Generated by Gemini', export: 'Export PDF', regenerate: 'Regenerate' },
  common: {
    offline: 'You are offline · Showing cached data',
    save: 'Save', cancel: 'Cancel', loading: 'Loading…',
  },
};

const mr = {
  app: { name: 'एडुअलॉकप्रो', tagline: 'शाळा बुद्धिमत्ता आणि शिक्षक नियुक्ती' },
  nav: {
    dashboard: 'डॅशबोर्ड', deploy: 'शिक्षक नियुक्ती', plan: 'जिल्हा योजना',
    briefing: 'AI ब्रीफिंग', schools: 'शाळा', teachers: 'शिक्षक', settings: 'सेटिंग्ज',
  },
  dashboard: {
    title: 'जिल्हा कमांड', district: 'नंदुरबार जिल्हा, महाराष्ट्र',
    vacancies: 'रिक्त जागा', critical: 'गंभीर शाळा', rte: 'RTE उल्लंघन', deployments: 'या आठवड्याच्या नियुक्त्या',
    rankedSchools: 'वंचितता निर्देशांकानुसार शाळा', search: '८४७ शाळा शोधा…', filters: 'फिल्टर',
    seeAll: 'सर्व ८४७ पहा', live: 'थेट',
  },
  school: {
    diScore: 'वंचितता निर्देशांक', dvs: 'नियुक्ती मूल्य स्कोअर', rteViolation: 'RTE उल्लंघन',
    vacancies: 'विषय रिक्त जागा', udise: 'UDISE+ डेटा', updated: 'अद्यतनित', deployTeacher: 'शिक्षक नियुक्त करा',
    viewBriefing: 'ब्रीफिंग पहा', critical: 'गंभीर', high: 'उच्च गरज', moderate: 'मध्यम', stable: 'स्थिर',
    pupils: 'विद्यार्थी', teachers: 'शिक्षक', ratio: 'PTR',
  },
  deploy: {
    title: 'शिक्षक नियुक्ती', subtitle: '{{school}} साठी AI-क्रमित उमेदवार',
    matchScore: 'मॅच स्कोअर', distance: 'अंतर', retention: 'टिकाव', experience: 'अनुभव',
    approve: 'नियुक्ती मंजूर करा', undo: 'पूर्ववत करा', deployed: 'नियुक्ती मंजूर · ३० सेकंदात पूर्ववत करा',
    rank: 'क्रम', subject: 'विषय', currentPosting: 'सध्याची नियुक्ती',
  },
  plan: {
    title: 'जिल्हा नियुक्ती योजना', subtitle: '{{count}} प्रलंबित नियुक्त्या',
    bulkApprove: 'निवडलेले एकत्र मंजूर करा', selected: '{{n}} निवडले',
  },
  briefing: { title: 'AI जिल्हा ब्रीफिंग', generated: 'Gemini द्वारे तयार', export: 'PDF निर्यात', regenerate: 'पुन्हा तयार करा' },
  common: { offline: 'तुम्ही ऑफलाइन आहात · संचयित डेटा दर्शवित आहे', save: 'जतन करा', cancel: 'रद्द करा', loading: 'लोड होत आहे…' },
};

const hi = {
  app: { name: 'एडुअलॉकप्रो', tagline: 'विद्यालय बुद्धिमत्ता और शिक्षक नियुक्ति' },
  nav: { dashboard: 'डैशबोर्ड', deploy: 'शिक्षक नियुक्ति', plan: 'जिला योजना', briefing: 'AI ब्रीफिंग', schools: 'विद्यालय', teachers: 'शिक्षक', settings: 'सेटिंग्स' },
  dashboard: { title: 'जिला कमांड', district: 'नंदुरबार जिला, महाराष्ट्र', vacancies: 'रिक्त पद', critical: 'गंभीर विद्यालय', rte: 'RTE उल्लंघन', deployments: 'इस सप्ताह की नियुक्तियाँ', rankedSchools: 'वंचितता सूचकांक के अनुसार विद्यालय', search: '847 विद्यालय खोजें…', filters: 'फ़िल्टर', seeAll: 'सभी 847 देखें', live: 'लाइव' },
  school: { diScore: 'वंचितता सूचकांक', dvs: 'नियुक्ति मूल्य स्कोर', rteViolation: 'RTE उल्लंघन', vacancies: 'विषय रिक्तियाँ', udise: 'UDISE+ डेटा', updated: 'अद्यतन', deployTeacher: 'शिक्षक नियुक्त करें', viewBriefing: 'ब्रीफिंग देखें', critical: 'गंभीर', high: 'उच्च आवश्यकता', moderate: 'मध्यम', stable: 'स्थिर', pupils: 'छात्र', teachers: 'शिक्षक', ratio: 'PTR' },
  deploy: { title: 'शिक्षक नियुक्ति', subtitle: '{{school}} के लिए AI-रैंकित उम्मीदवार', matchScore: 'मैच स्कोर', distance: 'दूरी', retention: 'प्रतिधारण', experience: 'अनुभव', approve: 'नियुक्ति स्वीकृत करें', undo: 'पूर्ववत करें', deployed: 'नियुक्ति स्वीकृत · 30 सेकंड में पूर्ववत करें', rank: 'रैंक', subject: 'विषय', currentPosting: 'वर्तमान पोस्टिंग' },
  plan: { title: 'जिला नियुक्ति योजना', subtitle: '{{count}} लंबित नियुक्तियाँ', bulkApprove: 'चयनित को एक साथ स्वीकृत करें', selected: '{{n}} चयनित' },
  briefing: { title: 'AI जिला ब्रीफिंग', generated: 'Gemini द्वारा तैयार', export: 'PDF निर्यात', regenerate: 'पुन: तैयार करें' },
  common: { offline: 'आप ऑफ़लाइन हैं · कैश्ड डेटा दिखा रहा है', save: 'सहेजें', cancel: 'रद्द करें', loading: 'लोड हो रहा है…' },
};

const te = {
  app: { name: 'ఎడ్యుఅలాక్‌ప్రో', tagline: 'పాఠశాల ఇంటెలిజెన్స్ & ఉపాధ్యాయ నియామకం' },
  nav: { dashboard: 'డాష్‌బోర్డ్', deploy: 'ఉపాధ్యాయ నియామకం', plan: 'జిల్లా ప్రణాళిక', briefing: 'AI బ్రీఫింగ్', schools: 'పాఠశాలలు', teachers: 'ఉపాధ్యాయులు', settings: 'సెట్టింగ్‌లు' },
  dashboard: { title: 'జిల్లా కమాండ్', district: 'నందుర్‌బార్ జిల్లా, మహారాష్ట్ర', vacancies: 'ఖాళీలు', critical: 'క్రిటికల్ పాఠశాలలు', rte: 'RTE ఉల్లంఘనలు', deployments: 'ఈ వారం నియామకాలు', rankedSchools: 'డిప్రివేషన్ ఇండెక్స్ ద్వారా పాఠశాలలు', search: '847 పాఠశాలలను శోధించండి…', filters: 'ఫిల్టర్‌లు', seeAll: 'మొత్తం 847 చూడండి', live: 'లైవ్' },
  school: { diScore: 'డిప్రివేషన్ ఇండెక్స్', dvs: 'డిప్లాయ్‌మెంట్ వాల్యూ స్కోర్', rteViolation: 'RTE ఉల్లంఘన', vacancies: 'సబ్జెక్ట్ ఖాళీలు', udise: 'UDISE+ డేటా', updated: 'నవీకరించబడింది', deployTeacher: 'ఉపాధ్యాయుడిని నియమించండి', viewBriefing: 'బ్రీఫింగ్ చూడండి', critical: 'క్రిటికల్', high: 'అధిక అవసరం', moderate: 'మధ్యస్థం', stable: 'స్థిరం', pupils: 'విద్యార్థులు', teachers: 'ఉపాధ్యాయులు', ratio: 'PTR' },
  deploy: { title: 'ఉపాధ్యాయ నియామకం', subtitle: '{{school}} కోసం AI-ర్యాంక్ చేసిన అభ్యర్థులు', matchScore: 'మ్యాచ్ స్కోర్', distance: 'దూరం', retention: 'నిలుపుదల', experience: 'అనుభవం', approve: 'నియామకాన్ని ఆమోదించండి', undo: 'రద్దు చేయండి', deployed: 'నియామకం ఆమోదించబడింది · 30 సెకన్లలో రద్దు చేయండి', rank: 'ర్యాంక్', subject: 'సబ్జెక్ట్', currentPosting: 'ప్రస్తుత పోస్టింగ్' },
  plan: { title: 'జిల్లా నియామక ప్రణాళిక', subtitle: '{{count}} పెండింగ్ నియామకాలు', bulkApprove: 'ఎంచుకున్నవి బల్క్ ఆమోదించండి', selected: '{{n}} ఎంచుకున్నారు' },
  briefing: { title: 'AI జిల్లా బ్రీఫింగ్', generated: 'Gemini ద్వారా రూపొందించబడింది', export: 'PDF ఎగుమతి', regenerate: 'తిరిగి రూపొందించండి' },
  common: { offline: 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు · కాష్ చేసిన డేటాను చూపుతోంది', save: 'సేవ్', cancel: 'రద్దు', loading: 'లోడ్ అవుతోంది…' },
};

const kn = {
  app: { name: 'ಎಡ್ಯುಅಲಾಕ್‌ಪ್ರೋ', tagline: 'ಶಾಲಾ ಇಂಟೆಲಿಜೆನ್ಸ್ ಮತ್ತು ಶಿಕ್ಷಕ ನಿಯೋಜನೆ' },
  nav: { dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', deploy: 'ಶಿಕ್ಷಕ ನಿಯೋಜನೆ', plan: 'ಜಿಲ್ಲಾ ಯೋಜನೆ', briefing: 'AI ಬ್ರೀಫಿಂಗ್', schools: 'ಶಾಲೆಗಳು', teachers: 'ಶಿಕ್ಷಕರು', settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು' },
  dashboard: { title: 'ಜಿಲ್ಲಾ ಕಮಾಂಡ್', district: 'ನಂದುರ್‌ಬಾರ್ ಜಿಲ್ಲೆ, ಮಹಾರಾಷ್ಟ್ರ', vacancies: 'ಖಾಲಿ ಹುದ್ದೆಗಳು', critical: 'ಗಂಭೀರ ಶಾಲೆಗಳು', rte: 'RTE ಉಲ್ಲಂಘನೆಗಳು', deployments: 'ಈ ವಾರದ ನಿಯೋಜನೆಗಳು', rankedSchools: 'ವಂಚನೆ ಸೂಚ್ಯಂಕದ ಪ್ರಕಾರ ಶಾಲೆಗಳು', search: '847 ಶಾಲೆಗಳನ್ನು ಹುಡುಕಿ…', filters: 'ಫಿಲ್ಟರ್‌ಗಳು', seeAll: 'ಎಲ್ಲಾ 847 ನೋಡಿ', live: 'ಲೈವ್' },
  school: { diScore: 'ವಂಚನೆ ಸೂಚ್ಯಂಕ', dvs: 'ನಿಯೋಜನೆ ಮೌಲ್ಯ ಸ್ಕೋರ್', rteViolation: 'RTE ಉಲ್ಲಂಘನೆ', vacancies: 'ವಿಷಯ ಖಾಲಿ ಹುದ್ದೆಗಳು', udise: 'UDISE+ ಡೇಟಾ', updated: 'ನವೀಕರಿಸಲಾಗಿದೆ', deployTeacher: 'ಶಿಕ್ಷಕರನ್ನು ನಿಯೋಜಿಸಿ', viewBriefing: 'ಬ್ರೀಫಿಂಗ್ ನೋಡಿ', critical: 'ಗಂಭೀರ', high: 'ಹೆಚ್ಚಿನ ಅಗತ್ಯ', moderate: 'ಮಧ್ಯಮ', stable: 'ಸ್ಥಿರ', pupils: 'ವಿದ್ಯಾರ್ಥಿಗಳು', teachers: 'ಶಿಕ್ಷಕರು', ratio: 'PTR' },
  deploy: { title: 'ಶಿಕ್ಷಕ ನಿಯೋಜನೆ', subtitle: '{{school}} ಗಾಗಿ AI-ಶ್ರೇಣಿಯ ಅಭ್ಯರ್ಥಿಗಳು', matchScore: 'ಮ್ಯಾಚ್ ಸ್ಕೋರ್', distance: 'ದೂರ', retention: 'ಧಾರಣ', experience: 'ಅನುಭವ', approve: 'ನಿಯೋಜನೆ ಅನುಮೋದಿಸಿ', undo: 'ರದ್ದುಮಾಡಿ', deployed: 'ನಿಯೋಜನೆ ಅನುಮೋದಿಸಲಾಗಿದೆ · 30 ಸೆಕೆಂಡುಗಳಲ್ಲಿ ರದ್ದುಮಾಡಿ', rank: 'ಶ್ರೇಣಿ', subject: 'ವಿಷಯ', currentPosting: 'ಪ್ರಸ್ತುತ ಪೋಸ್ಟಿಂಗ್' },
  plan: { title: 'ಜಿಲ್ಲಾ ನಿಯೋಜನೆ ಯೋಜನೆ', subtitle: '{{count}} ಬಾಕಿ ಇರುವ ನಿಯೋಜನೆಗಳು', bulkApprove: 'ಆಯ್ಕೆ ಮಾಡಿದವುಗಳನ್ನು ಬಲ್ಕ್ ಅನುಮೋದಿಸಿ', selected: '{{n}} ಆಯ್ಕೆಮಾಡಲಾಗಿದೆ' },
  briefing: { title: 'AI ಜಿಲ್ಲಾ ಬ್ರೀಫಿಂಗ್', generated: 'Gemini ನಿಂದ ರಚಿಸಲಾಗಿದೆ', export: 'PDF ರಫ್ತು', regenerate: 'ಮರು-ರಚಿಸಿ' },
  common: { offline: 'ನೀವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ · ಸಂಗ್ರಹಿತ ಡೇಟಾವನ್ನು ತೋರಿಸುತ್ತಿದೆ', save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದುಮಾಡಿ', loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ…' },
};

const ta = {
  app: { name: 'எடுஅலாக்ப்ரோ', tagline: 'பள்ளி நுண்ணறிவு & ஆசிரியர் நியமனம்' },
  nav: { dashboard: 'டாஷ்போர்டு', deploy: 'ஆசிரியர் நியமனம்', plan: 'மாவட்ட திட்டம்', briefing: 'AI பிரீஃபிங்', schools: 'பள்ளிகள்', teachers: 'ஆசிரியர்கள்', settings: 'அமைப்புகள்' },
  dashboard: { title: 'மாவட்ட கட்டளை', district: 'நந்துர்பார் மாவட்டம், மகாராஷ்டிரா', vacancies: 'காலி பணியிடங்கள்', critical: 'முக்கிய பள்ளிகள்', rte: 'RTE மீறல்கள்', deployments: 'இந்த வார நியமனங்கள்', rankedSchools: 'பற்றாக்குறை குறியீட்டின்படி பள்ளிகள்', search: '847 பள்ளிகளை தேடுங்கள்…', filters: 'வடிகட்டிகள்', seeAll: 'அனைத்து 847 ஐப் பார்க்க', live: 'நேரலை' },
  school: { diScore: 'பற்றாக்குறை குறியீடு', dvs: 'நியமன மதிப்பு மதிப்பெண்', rteViolation: 'RTE மீறல்', vacancies: 'பாட காலியிடங்கள்', udise: 'UDISE+ தரவு', updated: 'புதுப்பிக்கப்பட்டது', deployTeacher: 'ஆசிரியரை நியமி', viewBriefing: 'பிரீஃபிங் காண்க', critical: 'முக்கியம்', high: 'அதிக தேவை', moderate: 'மிதமான', stable: 'நிலையான', pupils: 'மாணவர்கள்', teachers: 'ஆசிரியர்கள்', ratio: 'PTR' },
  deploy: { title: 'ஆசிரியர் நியமனம்', subtitle: '{{school}} க்கான AI-தரப்படுத்தப்பட்ட வேட்பாளர்கள்', matchScore: 'பொருத்த மதிப்பெண்', distance: 'தூரம்', retention: 'தக்கவைப்பு', experience: 'அனுபவம்', approve: 'நியமனத்தை அங்கீகரி', undo: 'செயல்தவிர்', deployed: 'நியமனம் அங்கீகரிக்கப்பட்டது · 30 விநாடிகளில் செயல்தவிர்', rank: 'தரம்', subject: 'பாடம்', currentPosting: 'தற்போதைய பணி' },
  plan: { title: 'மாவட்ட நியமன திட்டம்', subtitle: '{{count}} நிலுவையில் உள்ள நியமனங்கள்', bulkApprove: 'தேர்ந்தெடுக்கப்பட்டவற்றை மொத்தமாக அங்கீகரி', selected: '{{n}} தேர்ந்தெடுக்கப்பட்டது' },
  briefing: { title: 'AI மாவட்ட பிரீஃபிங்', generated: 'Gemini ஆல் உருவாக்கப்பட்டது', export: 'PDF ஏற்றுமதி', regenerate: 'மீண்டும் உருவாக்கு' },
  common: { offline: 'நீங்கள் ஆஃப்லைனில் உள்ளீர்கள் · சேமிக்கப்பட்ட தரவு', save: 'சேமி', cancel: 'ரத்து', loading: 'ஏற்றுகிறது…' },
};

export const LANGUAGES = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'mr', label: 'Marathi', native: 'मराठी' },
  { code: 'hi', label: 'Hindi', native: 'हिंदी' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు' },
  { code: 'kn', label: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்' },
] as const;

i18n.use(initReactI18next).init({
  resources: {
    en: { translation: en }, mr: { translation: mr }, hi: { translation: hi },
    te: { translation: te }, kn: { translation: kn }, ta: { translation: ta },
  },
  lng: localStorage.getItem('eap-lang') || 'en',
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
});

i18n.on('languageChanged', (lng) => {
  document.documentElement.lang = lng;
  localStorage.setItem('eap-lang', lng);
});
document.documentElement.lang = i18n.language;

export default i18n;
