import { useState, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import { BRIEFING_TEXTS, STATS } from '@/data/mockData';
import { Sparkles, Download, RefreshCw, Check } from 'lucide-react';
import { toast } from 'sonner';
import jsPDF from 'jspdf';

export default function Briefing() {
  const { t, i18n } = useTranslation();
  const [variantIdx, setVariantIdx] = useState(0);
  const [regenerating, setRegenerating] = useState(false);
  const [justRegenerated, setJustRegenerated] = useState(false);
  const regenerateTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Get the available variants for the current language, fallback to English
  const lang = i18n.language;
  const variants = BRIEFING_TEXTS[lang] ?? BRIEFING_TEXTS['en'];
  const currentText = variants[variantIdx % variants.length];

  const regenerate = () => {
    if (regenerating) return;
    setRegenerating(true);
    setJustRegenerated(false);
    if (regenerateTimerRef.current) clearTimeout(regenerateTimerRef.current);
    // Simulate AI generation delay
    regenerateTimerRef.current = setTimeout(() => {
      setVariantIdx(prev => {
        const next = (prev + 1) % variants.length;
        return next;
      });
      setRegenerating(false);
      setJustRegenerated(true);
      toast.success(t('briefing.regenerate'), {
        description: lang === 'en' ? 'New AI briefing generated' : `${variants.length} variants available`,
        duration: 3000,
      });
      setTimeout(() => setJustRegenerated(false), 3000);
    }, 1400);
  };

  const exportPDF = () => {
    const doc = new jsPDF();
    // Title
    doc.setFontSize(18);
    doc.setTextColor(30, 30, 40);
    doc.text('EduAllocPro · District Briefing', 15, 22);
    // Subtitle
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 120);
    doc.text(`Nandurbar District · Generated by Gemini · ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, 15, 30);
    doc.text(`Language: ${lang.toUpperCase()} · Variant ${(variantIdx % variants.length) + 1} of ${variants.length}`, 15, 36);
    // Divider
    doc.setDrawColor(100, 100, 200);
    doc.setLineWidth(0.5);
    doc.line(15, 40, 195, 40);
    // Stats
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 80);
    doc.text(`Open Vacancies: ${STATS.vacancies}   Critical Schools: ${STATS.criticalSchools}   RTE Violations: ${STATS.rteViolations}`, 15, 48);
    // Body
    doc.setTextColor(20, 20, 30);
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(currentText, 180);
    doc.text(lines, 15, 58);
    doc.save(`nandurbar-briefing-${lang}-v${(variantIdx % variants.length) + 1}.pdf`);
    toast.success('PDF exported');
  };

  return (
    <div className="p-4 lg:p-6 max-w-4xl mx-auto space-y-5">
      {/* Header */}
      <div className="flex items-end justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl lg:text-3xl font-bold tracking-tight flex items-center gap-2">
            <Sparkles className="size-6 text-primary" /> {t('briefing.title')}
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            {t('briefing.generated')} · Nandurbar · 26 Apr 2026
            <span className="ml-2 text-xs px-1.5 py-0.5 rounded bg-surface-mid border border-border font-mono">
              v{(variantIdx % variants.length) + 1}/{variants.length}
            </span>
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={regenerate}
            disabled={regenerating}
            className="min-h-[44px] inline-flex items-center gap-2 px-4 rounded-md border border-border hover:border-primary/50 text-sm font-medium disabled:opacity-50 transition relative overflow-hidden"
          >
            {regenerating ? (
              <>
                <RefreshCw className="size-4 animate-spin" />
                <span>Generating…</span>
              </>
            ) : justRegenerated ? (
              <>
                <Check className="size-4 text-success" />
                <span className="text-success">{t('briefing.regenerate')}</span>
              </>
            ) : (
              <>
                <RefreshCw className="size-4" />
                <span>{t('briefing.regenerate')}</span>
              </>
            )}
            {/* shimmer overlay while generating */}
            {regenerating && (
              <span className="absolute inset-0 bg-gradient-to-r from-transparent via-primary/10 to-transparent animate-[shimmer_1s_infinite]" />
            )}
          </button>
          <button
            onClick={exportPDF}
            className="min-h-[44px] inline-flex items-center gap-2 px-4 rounded-md bg-gradient-brand text-primary-foreground font-semibold text-sm hover:shadow-glow transition"
          >
            <Download className="size-4" /> {t('briefing.export')}
          </button>
        </div>
      </div>

      {/* Stat cards */}
      <div className="grid grid-cols-3 gap-3">
        {[
          { l: t('dashboard.vacancies'), v: STATS.vacancies },
          { l: t('dashboard.critical'), v: STATS.criticalSchools },
          { l: t('dashboard.rte'), v: STATS.rteViolations },
        ].map((s, i) => (
          <div key={i} className="stat-card rounded-lg p-4">
            <div className="num-mono text-2xl font-bold">{s.v}</div>
            <div className="text-xs text-muted-foreground mt-1">{s.l}</div>
          </div>
        ))}
      </div>

      {/* Language variant indicator */}
      {variants.length > 1 && (
        <div className="flex gap-2 items-center">
          <span className="text-xs text-muted-foreground">Variants:</span>
          {variants.map((_, i) => (
            <button
              key={i}
              onClick={() => setVariantIdx(i)}
              className={`size-6 rounded-full text-[10px] font-bold transition ${
                i === variantIdx % variants.length
                  ? 'bg-primary text-primary-foreground shadow-glow'
                  : 'bg-surface-elevated border border-border text-muted-foreground hover:border-primary/50'
              }`}
            >
              {i + 1}
            </button>
          ))}
        </div>
      )}

      {/* Briefing body */}
      <div className={`rounded-lg border border-primary/30 bg-card p-6 relative overflow-hidden transition-all duration-300 ${regenerating ? 'opacity-40' : 'opacity-100'}`}>
        <div className="absolute top-0 inset-x-0 h-px bg-gradient-to-r from-transparent via-primary to-transparent" />
        <div className="absolute -top-20 -right-20 size-60 rounded-full bg-primary/10 blur-3xl pointer-events-none" />
        <div className="prose prose-invert max-w-none relative">
          {currentText.split('\n\n').map((p, i) => (
            <p key={i} className="text-[15px] leading-relaxed text-foreground/90 mb-4 last:mb-0 whitespace-pre-line">
              {p}
            </p>
          ))}
        </div>
      </div>

      {/* Gemini badge */}
      <div className="flex items-center gap-2 text-xs text-muted-foreground">
        <Sparkles className="size-3.5 text-primary" />
        <span>Powered by Gemini AI · Briefing updates every time you click Regenerate</span>
      </div>
    </div>
  );
}
